### ISSUE TITLE
генерация стран

### ISSUE THREAD

**Issue by chipitsine** [m-messiah/ip2geo#16]
```
MaxMind    | Generate cities                                              [OK]
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6e1d96, 0x16)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc044000000, 0x10000000, 0x9c0c18)
```

часто падает Out of memory.
оно страны генерирует не из специальной csv для стран ? из городов собирает ?

**Comment by chipitsine** [comment]
у travis-ci, кстати, памяти сильно меньше, чем на машинках, где я запускаю. может добавить в travis ? 


кстати, есть мысль - добавить в travis по крону (чтобы ловить моменты, когда, например, ipgeobase сломается окончательно)

**Comment by m-messiah** [comment]
Хм, у меня не падало.
Да собирает из городов, в том же проходе, где собирает города. 
В travis оно уже тестируется и не падает. 

Крон добавлю. Как улучшить сходу непонятно, попрофилирую на досуге

**Comment by chipitsine** [comment]
ну это же дорого, из городов. разве нет ?

**Comment by m-messiah** [comment]
Вот билд: https://travis-ci.org/m-messiah/ip2geo/builds/517137465
Прошел успешно, затраченную память без профайлера travis не пишет.

Из городов было бы дорого, если бы это было разными задачами, сейчас же просто при генерации городов туда же дописывается страна. Единственный поинт в том, что карта стран могла бы быть меньше за счет мерджа сетей, а сейчас она больше. Но ценой парсинга только одного файла вместо двух.

**Comment by chipitsine** [comment]
на всякий случай полный лог

```
           | Use output directory                                         [output]
ip2proxy   | Download                                                     [OK]
ip2proxy   | Unpack                                                       [OK]
TOR        | Torproject Download                                          [OK]
TOR        | Blutmagie Download                                           [OK]
TOR        | Merge                                                        [OK]
TOR        | Write nginx maps                                             [OK]
MaxMind    | Download                                                     [OK]
MaxMind    | Unpack                                                       [OK]
ip2proxy   | Parse                                                        [OK]
ip2proxy   | Write Nginx Map                                              [OK]
MaxMind    | Generate cities                                              [OK]
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6e1d96, 0x16)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc048000000, 0x10000000, 0x9c0c18)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x9a7960, 0x10000000, 0x7f8550174240, 0x7f854bffed20)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x9a7960, 0x7b63, 0x0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x9a7960, 0x7b63, 0x9c0c28, 0x20300100000000)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x9a7960, 0x7b63, 0x410100, 0x7f8551066c00)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x9a7960, 0x7b63, 0x7f854b010100, 0x7f854bffee58)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0xf6c6000, 0xc010780001, 0x1)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:1229

goroutine 20 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:311 fp=0xc000046ad8 sp=0xc000046ad0 pc=0x455940
runtime.mallocgc(0xf6c6000, 0x6bcd60, 0x1, 0xb50000c0057d3f00)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/malloc.go:913 +0x896 fp=0xc000046b78 sp=0xc000046ad8 pc=0x40d526
runtime.growslice(0x6bcd60, 0xc036da2000, 0x20e700, 0x20e700, 0x20e701, 0x1, 0x2, 0x20e700)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/slice.go:204 +0x145 fp=0xc000046be0 sp=0xc000046b78 pc=0x441455
main.(*MaxMind).Network(0xc000090120, 0xc0001c82a0, 0x6de6cc, 0xf)
	/home/travis/gopath/src/github.com/m-messiah/ip2geo/maxmind.go:119 +0x624 fp=0xc000046e58 sp=0xc000046be0 pc=0x63b7c4
main.Generate(0x729c60, 0xc000090120)
	/home/travis/gopath/src/github.com/m-messiah/ip2geo/common_geobase.go:42 +0x237 fp=0xc000046fd0 sp=0xc000046e58 pc=0x6373c7
runtime.goexit()
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000046fd8 sp=0xc000046fd0 pc=0x457a21
created by main.main
	/home/travis/gopath/src/github.com/m-messiah/ip2geo/app.go:75 +0x8f2

goroutine 1 [chan receive]:
main.main()
	/home/travis/gopath/src/github.com/m-messiah/ip2geo/app.go:89 +0x518

goroutine 46 [chan send]:
main.readCSVDatabase.func1(0xc0107817a0, 0xc00032e000, 0xd, 0xd, 0xc000320b20, 0x1d, 0x6d9c10, 0x7, 0x2c00320b00)
	/home/travis/gopath/src/github.com/m-messiah/ip2geo/utils.go:160 +0x3b7
created by main.readCSVDatabase
	/home/travis/gopath/src/github.com/m-messiah/ip2geo/utils.go:125 +0xc8

goroutine 30 [IO wait]:
internal/poll.runtime_pollWait(0x7f8557496d60, 0x72, 0xc000044a88)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000126a98, 0x72, 0xffffffffffffff00, 0x726960, 0x8cb3f0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000126a98, 0xc0001ca000, 0x1000, 0x1000)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000126a80, 0xc0001ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000126a80, 0xc0001ca000, 0x1000, 0x1000, 0xc000044b70, 0x454910, 0xc00006e600)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00008a0d0, 0xc0001ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/net.go:177 +0x68
net/http.(*persistConn).Read(0xc00014a240, 0xc0001ca000, 0x1000, 0x1000, 0xc000044c70, 0x4066d5, 0xc00006a9c0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/http/transport.go:1497 +0x75
bufio.(*Reader).fill(0xc00008cde0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc00008cde0, 0x1, 0x0, 0x0, 0x1, 0xc00006a900, 0x0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/bufio/bufio.go:132 +0x3f
net/http.(*persistConn).readLoop(0xc00014a240)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/http/transport.go:1645 +0x1a2
created by net/http.(*Transport).dialConn
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/http/transport.go:1338 +0x941

goroutine 31 [select]:
net/http.(*persistConn).writeLoop(0xc00014a240)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/http/transport.go:1885 +0x113
created by net/http.(*Transport).dialConn
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/http/transport.go:1339 +0x966
```

**Comment by chipitsine** [comment]
тестовая машинка в Microsoft Azure, 1Gb памяти.
генерация городов проходит, на странах умирает

```
TOR        | Write nginx maps                                             [OK]
MaxMind    | Generate cities                                              [OK]
Killed

```

```
[  682.257810] Out of memory: Kill process 5042 (ip2geo-linux64) score 733 or sacrifice child
```

на всякий случай в gdb (кажется, не сильнее информативно)

```
(gdb) run
Starting program: /home/ilia/./ip2geo-linux64 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff55e1700 (LWP 5249)]
[New Thread 0x7ffff4de0700 (LWP 5250)]
[New Thread 0x7ffff45df700 (LWP 5251)]
           | Use output directory                                         [output]
[New Thread 0x7ffff3dde700 (LWP 5252)]
MaxMind    | Download                                                     [OK]
MaxMind    | Unpack                                                       [OK]
[New Thread 0x7ffff305d700 (LWP 5253)]
TOR        | Torproject Download                                          [OK]
TOR        | Blutmagie Download                                           [OK]
TOR        | Merge                                                        [OK]
TOR        | Write nginx maps                                             [OK]
MaxMind    | Generate cities                                              [OK]
[Thread 0x7ffff305d700 (LWP 5253) exited]
[Thread 0x7ffff3dde700 (LWP 5252) exited]
[Thread 0x7ffff45df700 (LWP 5251) exited]
[Thread 0x7ffff4de0700 (LWP 5250) exited]
[Thread 0x7ffff55e1700 (LWP 5249) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
```

**Comment by m-messiah** [comment]
Окей, я понял что проблема есть, надо профилировать и оптимизировать.
gdb так сразу не покажет - там все в горутинах выполняется

**Comment by chipitsine** [comment]
без debuginfo - мало что покажет

**Comment by chipitsine** [comment]
"Duration: 1 minute 32 seconds "
